apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
  labels:
    app: mysqld-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqld-exporter
  template:
    metadata:
      labels:
        app: mysqld-exporter
    spec:
      containers:
      - name: mysqld-exporter
        image: prom/mysqld-exporter:latest
        env:
          - name: DATA_SOURCE_NAME
            value: "jose.marbae:Jm742569@tcp(mysql-service:3306)/forobmw"
        ports:
          - containerPort: 9104
