apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http-joseasir2
      port: 8081
      targetPort: 8081
      nodePort: 30081
    - name: https-joseasir2
      port: 444
      targetPort: 444
      nodePort: 30444
    - name: http-otro
      port: 8082
      targetPort: 8082
      nodePort: 30082
    - name: https-otro
      port: 8443
      targetPort: 8443
      nodePort: 30443