apiVersion: v1
kind: Service
metadata:
  name: nginx-service2
spec:
  type: LoadBalancer  # <- Cambiado de NodePort a LoadBalancer
  selector:
    app: nginx2
  ports:
    - name: http-joseasir2
      port: 8081         # Puerto expuesto externamente
      targetPort: 8081   # Puerto dentro del contenedor
    - name: https-joseasir2
      port: 444
      targetPort: 444
    - name: http-otro
      port: 8082
      targetPort: 8082
    - name: https-otro
      port: 8443
      targetPort: 8443
