apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 924529018629.dkr.ecr.us-east-1.amazonaws.com/nginx:v8
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-config
          mountPath: /etc/nginx/sites-available/  # Monte el volumen en la misma ruta
          readOnly: false
        - name: htpasswd-volume
          mountPath: /etc/nginx/.htpasswd
          subPath: htpasswd
          readOnly: true
      volumes:
      - name: web-config
        persistentVolumeClaim:
          claimName: pvc-config
      - name: htpasswd-volume
        secret:
          secretName: basic-auth  # El secret que creaste
          items:
            - key: htpasswd
              path: htpasswd

      imagePullSecrets:
      - name: ecr-secret
