apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx #este es el nombre que hace referencia a nuestro pod
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    nodePort: 30081
  - name: https
    port: 444
    targetPort: 444
    nodePort: 30444
