apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-webapp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # <- Agregar esto para que coincida con el PVC
  hostPath:
    path: /mnt/data/php
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-webapp
spec:
  volumeName: pv-webapp
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  #
