apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: mysql
        image: 533266989458.dkr.ecr.us-east-1.amazonaws.com/mysql:v8
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "my_passwd"
          - name: MYSQL_DATABASE
            value: "mi_basedatos"
          - name: MYSQL_USER
            value: "mi_usuario"
          - name: MYSQL_PASSWORD
            value: "my_passwd"
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
