apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-008a59aee9394b8e1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mysql-efs-sc
  resources:
    requests:
      storage: 5Gi
