name: Deploy to EKS

on:
  push:
    branches:
      - main  # Se ejecutará cuando hagas push a main
  workflow_dispatch:  # También permite ejecución manual desde GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1 

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name iliberis --region us-east-1

      - name: Apply Kubernetes manifests
        run: |
          # Desplegar MySQL
          kubectl apply -f my_playbook/roles/nginx/mysql.yaml
          kubectl apply -f my_playbook/roles/nginx/mysql-pv.yaml
          kubectl apply -f my_playbook/roles/nginx/mysql-service.yaml
          
          # Desplegar PHP
          kubectl apply -f my_playbook/roles/nginx/php-fpm.yaml
          kubectl apply -f my_playbook/roles/nginx/php-pv.yaml

          # Despliego nginx
          kubectl apply -f nginx-deployment2.yaml
          kubectl apply -f nginx-services2.yaml
          kubectl apply -f volumen2.yaml

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/nginx-deployment2
          kubectl rollout status deployment/mysql.yaml
          kubectl rollout status deployment/php-fpm.yaml
          
