name: Manage Monitoring Stack on EKS

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Selecciona deploy o destroy'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - destroy

jobs:
  manage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name iliberis --region us-east-1

      - name: Deploy or Destroy Prometheus & Grafana
        run: |
          if [ "${{ github.event.inputs.action }}" = "deploy" ]; then
            helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
            helm repo update
            helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
              --namespace monitoring --create-namespace \
              --set grafana.service.type=LoadBalancer \
              --set grafana.additionalDataSources[0].name=Prometheus \
              --set grafana.additionalDataSources[0].type=prometheus \
              --set grafana.additionalDataSources[0].url=http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090 \
              --set grafana.additionalDataSources[0].access=proxy \
              --set grafana.additionalDataSources[0].isDefault=true
 
          else
            helm uninstall monitoring --namespace monitoring || echo "No existe release para desinstalar"
            kubectl delete namespace monitoring || echo "No existe namespace para borrar"
          fi
